site_name: Drinks Guide
theme:
  name: material
  features:
    - navigation.expand

nav:
  - Рецепты напитков:
      - Чай: tea.md
      - Кофе: coffee.md
      - Какао: cocoa.md
      - Глинтвейн: glintvein.md
